// ================================================================
//  Doctor AI Scan — Brain Tumor MRI Classification
//  Teachable Machine (TF.js) · Background Loading · Medical Guidance
// ================================================================

const MODEL_PATH = './tm-my-image-model/';

// ---- State ----
let model       = null;
let modelReady  = false;
let imgSrc      = null;
let stream      = null;
let currentLang = localStorage.getItem('dais-lang') || 'en';

// ---- DOM ----
const $status       = document.getElementById('model-status');
const $statusText   = document.getElementById('status-text');
const $dropzone     = document.getElementById('dropzone');
const $dzDefault    = document.getElementById('dz-default');
const $preview      = document.getElementById('preview');
const $previewImg   = document.getElementById('preview-img');
const $fileInput    = document.getElementById('file-input');
const $btnScan      = document.getElementById('btn-scan');
const $resultsBox   = document.getElementById('results-box');
const $camFeed      = document.getElementById('cam-feed');
const $camPh        = document.getElementById('cam-ph');
const $btnCamStart  = document.getElementById('btn-cam-start');
const $btnCapture   = document.getElementById('btn-capture');
const $btnCamStop   = document.getElementById('btn-cam-stop');
const $panelUpload  = document.getElementById('panel-upload');
const $panelCamera  = document.getElementById('panel-camera');
const $tabUpload    = document.getElementById('tab-upload');
const $tabCamera    = document.getElementById('tab-camera');
const $langDD       = document.getElementById('lang-dd');

// ================================================================
//  TRANSLATIONS
// ================================================================
const T = {
  en: {
    status_loading: 'Loading…',
    status_ready: 'Ready',
    status_error: 'Error',
    hero_title: 'Brain Tumor <em>Detection</em>',
    hero_desc: 'Upload or capture a brain MRI scan and let AI assist your diagnosis in seconds',
    tab_upload: 'Upload',
    tab_camera: 'Camera',
    drop_title: 'Drop MRI Scan Here',
    drop_desc: 'or <b>tap to browse</b> — PNG, JPG, WEBP',
    cam_placeholder: 'Camera preview appears here',
    btn_start: 'Start',
    btn_capture: 'Capture',
    btn_stop: 'Stop',
    btn_analyze: 'Analyze MRI Scan',
    feat1_title: 'Deep Learning',
    feat1_desc: 'Neural network trained on brain MRI scans',
    feat2_title: 'Instant',
    feat2_desc: 'Analysis in seconds — all in your browser',
    feat3_title: 'Private',
    feat3_desc: 'Images never leave your device',
    footer_role: 'Clinical Decision Support Tool',
    footer_notice: 'This system is designed to assist — not replace — qualified medical professionals.<br/>Always seek formal diagnosis from a certified physician.',
    res_title: 'Analysis Results',
    bar_tumor: 'Tumor Detected',
    bar_clear: 'No Tumor',
    bar_notmri: 'Not MRI Scan',
    dx_tumor_t: 'Tumor Indicators Detected',
    dx_tumor_d: 'AI detected possible tumor signs with {pct}% confidence.',
    dx_clear_t: 'No Tumor Indicators Detected',
    dx_clear_d: 'MRI scan appears within normal range — {pct}% confidence.',
    dx_notmri_t: 'This Is Not a Brain MRI Scan',
    dx_notmri_d: 'The uploaded image does not appear to be a brain MRI scan. Please follow the instructions below to upload a valid image.',
    disclaimer: '<strong>⚕️ Important Medical Notice:</strong> Doctor AI Scan is a <strong>clinical decision support tool</strong> designed to assist qualified healthcare professionals in the preliminary screening of brain MRI scans. This system is <strong>not a substitute for professional medical diagnosis</strong>, clinical examination, or the judgment of a certified radiologist or neurologist. All results generated by this AI must be validated by a licensed physician before any clinical decisions are made. The developers bear no liability for decisions based solely on this tool\'s output. If you are a patient, please consult your attending physician for a comprehensive evaluation.',
    guide_tumor_title: 'Medical Guidance — Tumor Indicators Detected',
    guide_tumor_body: '<p>The AI analysis has identified <strong>potential indicators consistent with the presence of a brain tumor</strong> in this MRI scan with a confidence level of <strong>{pct}%</strong>. Based on this preliminary finding, the following clinical steps are recommended:</p><ul><li><strong>Urgent Radiological Review:</strong> This scan should be reviewed immediately by a board-certified <strong>neuroradiologist</strong> for a detailed interpretation, including assessment of tumor size, location, morphology, and potential grade classification.</li><li><strong>Contrast-Enhanced MRI:</strong> If this scan was performed without gadolinium contrast, a <strong>contrast-enhanced MRI (CE-MRI)</strong> is strongly recommended to better delineate tumor margins, evaluate blood-brain barrier integrity, and assess enhancement patterns.</li><li><strong>Neurology Consultation:</strong> The patient should be referred to a <strong>neurologist or neurosurgeon</strong> for a comprehensive clinical evaluation, including detailed neurological examination and symptom assessment.</li><li><strong>Advanced Imaging:</strong> Consider additional imaging modalities such as <strong>MR Spectroscopy (MRS)</strong>, <strong>Perfusion MRI</strong>, or <strong>PET-CT</strong> for further characterization of the lesion and differentiation between tumor subtypes.</li><li><strong>Histopathological Confirmation:</strong> Definitive diagnosis requires <strong>tissue biopsy and histopathological analysis</strong>. A stereotactic biopsy or surgical resection may be indicated depending on the lesion\'s characteristics and accessibility.</li><li><strong>Multidisciplinary Tumor Board:</strong> Present the case to a <strong>multidisciplinary tumor board</strong> (radiology, neurosurgery, oncology, pathology) for consensus on the optimal management plan.</li></ul><p><strong>Note for the Patient:</strong> This AI finding is a <em>preliminary screening result</em>, not a confirmed diagnosis. Many lesions detected on MRI may be benign or represent non-neoplastic conditions. Only your physician, after a thorough evaluation, can determine the actual nature of any findings.</p>',
    guide_clear_title: 'Medical Guidance — Normal Screening Result',
    guide_clear_body: '<p>The AI analysis indicates <strong>no significant tumor indicators</strong> in this brain MRI scan with a confidence level of <strong>{pct}%</strong>. While this is a positive preliminary finding, please note the following:</p><ul><li><strong>Clinical Correlation Required:</strong> A normal AI screening result does <strong>not exclude all pathologies</strong>. If the patient presents with clinical symptoms (headaches, seizures, neurological deficits, visual disturbances), further evaluation by a specialist remains essential.</li><li><strong>Radiologist Review:</strong> This scan should still be formally reported by a qualified <strong>radiologist</strong> as part of standard clinical protocol. AI screening is a supplementary tool, not a replacement for expert interpretation.</li><li><strong>Limitations:</strong> This AI model was trained on specific types of brain tumors and may not detect all categories of intracranial pathology, including but not limited to: <strong>small metastases, low-grade diffuse gliomas, vascular malformations,</strong> or <strong>non-mass-forming lesions</strong>.</li><li><strong>Follow-up Imaging:</strong> If clinically indicated (e.g., persistent symptoms, family history of brain tumors, known primary malignancy elsewhere), consider <strong>follow-up MRI in 3-6 months</strong> as per clinical guidelines.</li><li><strong>Routine Health Monitoring:</strong> Continue routine health check-ups and immediately report any new or worsening neurological symptoms to your healthcare provider.</li></ul><p><strong>Note for the Patient:</strong> A negative screening result is reassuring but should always be discussed with your physician in the context of your complete medical history and symptoms.</p>',
    guide_notmri_title: 'Usage Guidance — Invalid Input Image',
    guide_notmri_body: '<p>The AI system has determined that the uploaded image <strong>does not appear to be a brain MRI scan</strong>. To obtain accurate analysis results, please ensure the following:</p><ul><li><strong>Image Type:</strong> Upload a <strong>brain MRI scan</strong> — preferably an axial (transverse) cross-sectional view in T1-weighted, T2-weighted, or FLAIR sequence.</li><li><strong>Image Quality:</strong> The image should be clear, properly oriented, and free of significant artifacts. Avoid photographs of screens — use direct digital exports (DICOM to JPEG/PNG).</li><li><strong>Supported Formats:</strong> JPEG, PNG, or WEBP formats are accepted. The image will be automatically resized to 224×224 pixels for model inference.</li><li><strong>Common Errors:</strong> CT scans, X-rays, ultrasound images, photographs of patients, or non-medical images will be rejected by the classification model.</li></ul><p>Please upload a valid brain MRI image and try again.</p>',
    model_loading_alert: 'Model is still loading — please wait a few seconds.',
  },
  ar: {
    status_loading: 'جارٍ التحميل…',
    status_ready: 'جاهز',
    status_error: 'خطأ',
    hero_title: 'كشف أورام <em>الدماغ</em>',
    hero_desc: 'قم برفع أو التقاط صورة أشعة رنين مغناطيسي للدماغ ودع الذكاء الاصطناعي يساعد في التشخيص خلال ثوانٍ',
    tab_upload: 'رفع صورة',
    tab_camera: 'الكاميرا',
    drop_title: 'اسحب صورة MRI هنا',
    drop_desc: 'أو <b>انقر للتصفح</b> — PNG, JPG, WEBP',
    cam_placeholder: 'ستظهر معاينة الكاميرا هنا',
    btn_start: 'تشغيل',
    btn_capture: 'التقاط',
    btn_stop: 'إيقاف',
    btn_analyze: 'تحليل صورة الأشعة',
    feat1_title: 'تعلم عميق',
    feat1_desc: 'شبكة عصبية مدربة على صور أشعة الدماغ',
    feat2_title: 'نتائج فورية',
    feat2_desc: 'تحليل في ثوانٍ — الكل يعمل في متصفحك',
    feat3_title: 'خصوصية تامة',
    feat3_desc: 'صورك لا تغادر جهازك أبداً',
    footer_role: 'أداة دعم القرار السريري',
    footer_notice: 'هذا النظام مصمّم لـ<strong>مساعدة</strong> المختصين الطبيين المؤهلين — وليس لاستبدالهم.<br/>استشر دائماً طبيباً معتمداً للحصول على تشخيص رسمي.',
    res_title: 'نتائج التحليل',
    bar_tumor: 'تم اكتشاف ورم',
    bar_clear: 'لا يوجد ورم',
    bar_notmri: 'ليست صورة MRI',
    dx_tumor_t: 'تم اكتشاف مؤشرات ورم',
    dx_tumor_d: 'اكتشف الذكاء الاصطناعي مؤشرات محتملة لوجود ورم بنسبة ثقة {pct}%.',
    dx_clear_t: 'لم يتم اكتشاف مؤشرات ورم',
    dx_clear_d: 'تبدو صورة الأشعة ضمن النطاق الطبيعي — بنسبة ثقة {pct}%.',
    dx_notmri_t: 'هذه ليست صورة أشعة رنين مغناطيسي للدماغ',
    dx_notmri_d: 'الصورة المرفوعة لا تبدو صورة MRI للدماغ. يرجى اتباع الإرشادات أدناه لرفع صورة صالحة.',
    disclaimer: '<strong>⚕️ إشعار طبي هام:</strong> نظام Doctor AI Scan هو <strong>أداة دعم للقرار السريري</strong> مصمّمة لمساعدة المهنيين الطبيين المؤهلين في الفحص الأولي لصور أشعة الرنين المغناطيسي للدماغ. هذا النظام <strong>ليس بديلاً عن التشخيص الطبي المهني</strong> أو الفحص السريري أو حكم أخصائي الأشعة أو طبيب الأعصاب المعتمد. يجب التحقق من صحة جميع النتائج من قبل طبيب مرخّص قبل اتخاذ أي قرارات سريرية. لا يتحمل المطورون أي مسؤولية عن القرارات المبنية حصرياً على مخرجات هذه الأداة. إذا كنت مريضاً، يرجى استشارة طبيبك المعالج لإجراء تقييم شامل.',
    guide_tumor_title: 'التوجيه الطبي — مؤشرات ورم مكتشفة',
    guide_tumor_body: '<p>حدد التحليل بالذكاء الاصطناعي <strong>مؤشرات محتملة تتوافق مع وجود ورم في الدماغ</strong> في هذه الأشعة بمستوى ثقة <strong>{pct}%</strong>. بناءً على هذا الاكتشاف الأولي، يُوصى بالخطوات السريرية التالية:</p><ul><li><strong>مراجعة إشعاعية عاجلة:</strong> يجب مراجعة هذه الأشعة فوراً من قبل <strong>أخصائي أشعة عصبية معتمد</strong> لتفسير مفصل يشمل تقييم حجم الورم وموقعه وشكله ودرجته المحتملة.</li><li><strong>تصوير بالرنين المغناطيسي المعزز بالتباين:</strong> إذا تم إجراء هذا الفحص بدون صبغة الجادولينيوم، يُوصى بشدة بإجراء <strong>تصوير رنين مغناطيسي معزز بالتباين (CE-MRI)</strong> لتحديد حدود الورم بشكل أفضل.</li><li><strong>استشارة طب الأعصاب:</strong> يجب تحويل المريض إلى <strong>طبيب أعصاب أو جراح أعصاب</strong> لإجراء تقييم سريري شامل يشمل فحصاً عصبياً مفصلاً.</li><li><strong>التصوير المتقدم:</strong> النظر في أساليب تصوير إضافية مثل <strong>التحليل الطيفي بالرنين المغناطيسي (MRS)</strong> أو <strong>تصوير الرنين المغناطيسي بالتروية</strong> أو <strong>PET-CT</strong>.</li><li><strong>التأكيد النسيجي المرضي:</strong> التشخيص النهائي يتطلب <strong>خزعة نسيجية وتحليل باثولوجي</strong>.</li><li><strong>مجلس الأورام متعدد التخصصات:</strong> عرض الحالة على <strong>مجلس أورام متعدد التخصصات</strong> للتوافق على خطة العلاج المثلى.</li></ul><p><strong>ملاحظة للمريض:</strong> هذا الاكتشاف بالذكاء الاصطناعي هو <em>نتيجة فحص أولية</em> وليس تشخيصاً مؤكداً. العديد من الآفات المكتشفة بالأشعة قد تكون حميدة. طبيبك وحده قادر على تحديد طبيعة أي نتائج بعد تقييم شامل.</p>',
    guide_clear_title: 'التوجيه الطبي — نتيجة فحص طبيعية',
    guide_clear_body: '<p>يشير تحليل الذكاء الاصطناعي إلى <strong>عدم وجود مؤشرات ورم ملحوظة</strong> في هذه الأشعة بمستوى ثقة <strong>{pct}%</strong>. مع أن هذا اكتشاف أولي إيجابي، يرجى ملاحظة التالي:</p><ul><li><strong>الارتباط السريري مطلوب:</strong> نتيجة الفحص الطبيعية بالذكاء الاصطناعي <strong>لا تستبعد جميع الأمراض</strong>. إذا كان المريض يعاني من أعراض سريرية (صداع، نوبات صرع، عجز عصبي)، فإن التقييم الإضافي من متخصص يظل ضرورياً.</li><li><strong>مراجعة أخصائي الأشعة:</strong> يجب تقييم هذه الأشعة رسمياً من قبل <strong>أخصائي أشعة</strong> معتمد كجزء من البروتوكول السريري القياسي.</li><li><strong>القيود:</strong> هذا النموذج مدرب على أنواع محددة من أورام الدماغ وقد لا يكتشف جميع أنواع الأمراض داخل الجمجمة.</li><li><strong>تصوير المتابعة:</strong> إذا كان مؤشراً سريرياً، فكّر في <strong>متابعة بالرنين المغناطيسي خلال 3-6 أشهر</strong>.</li><li><strong>المراقبة الصحية الروتينية:</strong> واصل الفحوصات الصحية الروتينية وأبلغ فوراً عن أي أعراض عصبية جديدة.</li></ul><p><strong>ملاحظة للمريض:</strong> نتيجة الفحص السلبية مطمئنة لكن يجب دائماً مناقشتها مع طبيبك في سياق تاريخك الطبي الكامل.</p>',
    guide_notmri_title: 'إرشادات الاستخدام — صورة غير صالحة',
    guide_notmri_body: '<p>حدد نظام الذكاء الاصطناعي أن الصورة المرفوعة <strong>لا تبدو صورة أشعة رنين مغناطيسي للدماغ</strong>. للحصول على نتائج تحليل دقيقة، يرجى التأكد مما يلي:</p><ul><li><strong>نوع الصورة:</strong> ارفع <strong>صورة أشعة رنين مغناطيسي للدماغ</strong> — يُفضل مقطع محوري (عرضي) بتسلسل T1 أو T2 أو FLAIR.</li><li><strong>جودة الصورة:</strong> يجب أن تكون الصورة واضحة وموجهة بشكل صحيح وخالية من العيوب. تجنب تصوير الشاشات — استخدم التصدير الرقمي المباشر.</li><li><strong>الصيغ المدعومة:</strong> صيغ JPEG و PNG و WEBP مقبولة.</li><li><strong>أخطاء شائعة:</strong> أشعة CT، الأشعة السينية، صور الموجات فوق الصوتية، صور المرضى، أو الصور غير الطبية سيتم رفضها.</li></ul><p>يرجى رفع صورة أشعة رنين مغناطيسي صالحة والمحاولة مرة أخرى.</p>',
    model_loading_alert: 'النموذج لا يزال قيد التحميل — يرجى الانتظار بضع ثوانٍ.',
  },
  fr: {
    status_loading: 'Chargement…',
    status_ready: 'Prêt',
    status_error: 'Erreur',
    hero_title: 'Détection de tumeurs <em>cérébrales</em>',
    hero_desc: 'Téléchargez ou capturez une IRM cérébrale et laissez l\'IA assister votre diagnostic en quelques secondes',
    tab_upload: 'Télécharger',
    tab_camera: 'Caméra',
    drop_title: 'Déposez l\'IRM ici',
    drop_desc: 'ou <b>cliquez pour parcourir</b> — PNG, JPG, WEBP',
    cam_placeholder: 'L\'aperçu de la caméra apparaîtra ici',
    btn_start: 'Démarrer',
    btn_capture: 'Capturer',
    btn_stop: 'Arrêter',
    btn_analyze: 'Analyser l\'IRM',
    feat1_title: 'Deep Learning',
    feat1_desc: 'Réseau neuronal entraîné sur des IRM cérébrales',
    feat2_title: 'Instantané',
    feat2_desc: 'Analyse en secondes — tout dans votre navigateur',
    feat3_title: 'Privé',
    feat3_desc: 'Vos images ne quittent jamais votre appareil',
    footer_role: 'Outil d\'Aide à la Décision Clinique',
    footer_notice: 'Ce système est conçu pour <strong>assister</strong> — et non remplacer — les professionnels médicaux qualifiés.<br/>Consultez toujours un médecin certifié pour un diagnostic formel.',
    res_title: 'Résultats de l\'Analyse',
    bar_tumor: 'Tumeur Détectée',
    bar_clear: 'Pas de Tumeur',
    bar_notmri: 'Pas une IRM',
    dx_tumor_t: 'Indicateurs de Tumeur Détectés',
    dx_tumor_d: 'L\'IA a détecté des signes possibles de tumeur avec {pct}% de confiance.',
    dx_clear_t: 'Aucun Indicateur de Tumeur Détecté',
    dx_clear_d: 'L\'IRM semble dans la plage normale — {pct}% de confiance.',
    dx_notmri_t: 'Ceci n\'est pas une IRM cérébrale',
    dx_notmri_d: 'L\'image téléchargée ne semble pas être une IRM cérébrale. Veuillez suivre les instructions ci-dessous pour télécharger une image valide.',
    disclaimer: '<strong>⚕️ Avis Médical Important :</strong> Doctor AI Scan est un <strong>outil d\'aide à la décision clinique</strong> conçu pour assister les professionnels de santé qualifiés dans le dépistage préliminaire des IRM cérébrales. Ce système <strong>ne remplace pas le diagnostic médical professionnel</strong>, l\'examen clinique ou le jugement d\'un radiologue ou neurologue certifié. Tous les résultats générés par cette IA doivent être validés par un médecin agréé avant toute décision clinique. Les développeurs déclinent toute responsabilité pour les décisions basées uniquement sur les résultats de cet outil. Si vous êtes un patient, veuillez consulter votre médecin traitant pour une évaluation complète.',
    guide_tumor_title: 'Orientation Médicale — Indicateurs de Tumeur Détectés',
    guide_tumor_body: '<p>L\'analyse IA a identifié des <strong>indicateurs potentiels compatibles avec la présence d\'une tumeur cérébrale</strong> dans cette IRM avec un niveau de confiance de <strong>{pct}%</strong>. Sur la base de cette constatation préliminaire, les étapes cliniques suivantes sont recommandées :</p><ul><li><strong>Revue Radiologique Urgente :</strong> Cette IRM doit être examinée immédiatement par un <strong>neuroradiologue certifié</strong> pour une interprétation détaillée.</li><li><strong>IRM avec Contraste :</strong> Si cette IRM a été réalisée sans gadolinium, une <strong>IRM avec contraste (CE-IRM)</strong> est fortement recommandée.</li><li><strong>Consultation Neurologique :</strong> Le patient doit être orienté vers un <strong>neurologue ou neurochirurgien</strong> pour une évaluation clinique complète.</li><li><strong>Imagerie Avancée :</strong> Envisager des modalités supplémentaires telles que la <strong>spectroscopie RM (MRS)</strong>, l\'<strong>IRM de perfusion</strong> ou le <strong>PET-CT</strong>.</li><li><strong>Confirmation Histopathologique :</strong> Le diagnostic définitif nécessite une <strong>biopsie tissulaire et une analyse histopathologique</strong>.</li><li><strong>Réunion de Concertation Pluridisciplinaire :</strong> Présenter le cas à un <strong>comité multidisciplinaire</strong> pour un consensus sur le plan de prise en charge optimal.</li></ul><p><strong>Note au Patient :</strong> Ce résultat IA est un <em>dépistage préliminaire</em>, pas un diagnostic confirmé. Seul votre médecin, après une évaluation approfondie, peut déterminer la nature réelle de toute anomalie.</p>',
    guide_clear_title: 'Orientation Médicale — Résultat de Dépistage Normal',
    guide_clear_body: '<p>L\'analyse IA indique <strong>aucun indicateur significatif de tumeur</strong> dans cette IRM cérébrale avec un niveau de confiance de <strong>{pct}%</strong>. Bien que ce soit un résultat préliminaire positif, veuillez noter :</p><ul><li><strong>Corrélation Clinique Requise :</strong> Un résultat IA normal <strong>n\'exclut pas toutes les pathologies</strong>. Si le patient présente des symptômes cliniques, une évaluation spécialisée reste essentielle.</li><li><strong>Revue Radiologique :</strong> Cette IRM doit être formellement interprétée par un <strong>radiologue</strong> qualifié.</li><li><strong>Limitations :</strong> Ce modèle IA a été entraîné sur des types spécifiques de tumeurs cérébrales et peut ne pas détecter toutes les pathologies intracrâniennes.</li><li><strong>Imagerie de Suivi :</strong> Si cliniquement indiqué, envisager un <strong>suivi IRM dans 3-6 mois</strong>.</li><li><strong>Surveillance de Routine :</strong> Poursuivre les bilans de santé routiniers et signaler immédiatement tout nouveau symptôme neurologique.</li></ul><p><strong>Note au Patient :</strong> Un résultat négatif est rassurant mais doit toujours être discuté avec votre médecin.</p>',
    guide_notmri_title: 'Guide d\'Utilisation — Image Non Valide',
    guide_notmri_body: '<p>Le système IA a déterminé que l\'image téléchargée <strong>ne semble pas être une IRM cérébrale</strong>. Pour obtenir des résultats précis, veuillez vous assurer de :</p><ul><li><strong>Type d\'Image :</strong> Téléchargez une <strong>IRM cérébrale</strong> — de préférence une coupe axiale (transversale) en séquence T1, T2 ou FLAIR.</li><li><strong>Qualité d\'Image :</strong> L\'image doit être claire, correctement orientée et sans artefacts significatifs. Évitez les photos d\'écrans.</li><li><strong>Formats Supportés :</strong> JPEG, PNG ou WEBP sont acceptés.</li><li><strong>Erreurs Courantes :</strong> Les scanners CT, radiographies, échographies, photos de patients ou images non médicales seront rejetés.</li></ul><p>Veuillez télécharger une image IRM cérébrale valide et réessayer.</p>',
    model_loading_alert: 'Le modèle est encore en cours de chargement — veuillez patienter quelques secondes.',
  }
};

function t(key, replacements) {
  let str = (T[currentLang] && T[currentLang][key]) || T['en'][key] || key;
  if (replacements) {
    for (const [k, v] of Object.entries(replacements)) {
      str = str.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
    }
  }
  return str;
}

// ================================================================
//  LANGUAGE SYSTEM
// ================================================================
function setLanguage(lang) {
  currentLang = lang;
  localStorage.setItem('dais-lang', lang);

  // Update dir for RTL
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';

  // Update all data-i18n elements
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    el.innerHTML = t(key);
  });

  // Update model status text based on current state
  if (modelReady) {
    $statusText.innerHTML = t('status_ready');
  } else if ($status.classList.contains('loading')) {
    $statusText.innerHTML = t('status_loading');
  }

  // Update dropdown active state
  $langDD.querySelectorAll('button').forEach(btn => {
    btn.classList.toggle('active', btn.dataset.lang === lang);
  });

  closeLangDropdown();
}

function toggleLangDropdown() {
  $langDD.classList.toggle('open');
}

function closeLangDropdown() {
  $langDD.classList.remove('open');
}

// Close dropdown when clicking outside
document.addEventListener('click', (e) => {
  if (!e.target.closest('.lang-wrap')) closeLangDropdown();
});

// ================================================================
//  DARK MODE
// ================================================================
function toggleDarkMode() {
  document.body.classList.toggle('dark');
  const isDark = document.body.classList.contains('dark');
  localStorage.setItem('dais-theme', isDark ? 'dark' : 'light');
  document.querySelector('meta[name="theme-color"]').content = isDark ? '#0F1420' : '#2B7AE9';
}

function initTheme() {
  const saved = localStorage.getItem('dais-theme');
  if (saved === 'dark' || (!saved && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
    document.body.classList.add('dark');
    document.querySelector('meta[name="theme-color"]').content = '#0F1420';
  }
}

// ================================================================
//  1 · Load model in background (non-blocking)
// ================================================================
function waitForLibs() {
  return new Promise((resolve) => {
    const check = () => {
      if (typeof tmImage !== 'undefined' && typeof tf !== 'undefined') resolve();
      else setTimeout(check, 200);
    };
    check();
  });
}

async function loadModel() {
  try {
    await waitForLibs();
    model = await tmImage.load(MODEL_PATH + 'model.json', MODEL_PATH + 'metadata.json');
    modelReady = true;
    $status.classList.remove('loading');
    $status.classList.add('ready');
    $statusText.textContent = t('status_ready');
    console.log('Model loaded —', model.getTotalClasses(), 'classes');
  } catch (e) {
    console.error('Model load error:', e);
    $statusText.textContent = t('status_error');
    $status.style.background = '#FFF0F0';
    $status.style.color = '#E54D4D';
  }
}

// ================================================================
//  2 · Tabs
// ================================================================
function switchTab(tab) {
  if (tab === 'upload') {
    $tabUpload.classList.add('active'); $tabCamera.classList.remove('active');
    $panelUpload.classList.add('active'); $panelCamera.classList.remove('active');
    stopCamera();
  } else {
    $tabCamera.classList.add('active'); $tabUpload.classList.remove('active');
    $panelCamera.classList.add('active'); $panelUpload.classList.remove('active');
  }
}

// ================================================================
//  3 · File upload & drag-drop
// ================================================================
$fileInput.addEventListener('change', e => { if (e.target.files[0]) handleFile(e.target.files[0]); });

$dropzone.addEventListener('dragover', e => { e.preventDefault(); $dropzone.classList.add('drag'); });
$dropzone.addEventListener('dragleave', () => $dropzone.classList.remove('drag'));
$dropzone.addEventListener('drop', e => {
  e.preventDefault(); $dropzone.classList.remove('drag');
  const f = e.dataTransfer.files[0];
  if (f && f.type.startsWith('image/')) handleFile(f);
});

function handleFile(file) {
  const r = new FileReader();
  r.onload = ev => { imgSrc = ev.target.result; showPreview(imgSrc); };
  r.readAsDataURL(file);
}

function showPreview(src) {
  $previewImg.src = src;
  $preview.classList.add('show');
  $dzDefault.style.display = 'none';
  $dropzone.classList.add('has-img');
  $btnScan.disabled = !modelReady;
  $resultsBox.innerHTML = '';
}

function clearImage(e) {
  if (e) e.stopPropagation();
  imgSrc = null;
  $previewImg.src = '';
  $preview.classList.remove('show');
  $dzDefault.style.display = '';
  $dropzone.classList.remove('has-img');
  $fileInput.value = '';
  $btnScan.disabled = true;
  $resultsBox.innerHTML = '';
}

// ================================================================
//  4 · Camera
// ================================================================
async function startCamera() {
  try {
    stream = await navigator.mediaDevices.getUserMedia({
      video: { facingMode: 'environment', width: { ideal: 640 }, height: { ideal: 480 } }
    });
    $camFeed.srcObject = stream;
    $camFeed.classList.add('on');
    $camPh.style.display = 'none';
    $btnCamStart.disabled = true;
    $btnCapture.disabled = false;
    $btnCamStop.classList.remove('hidden');
  } catch (err) {
    alert('Cannot access camera — check permissions.');
  }
}

function capturePhoto() {
  if (!stream) return;
  const c = document.createElement('canvas');
  c.width = $camFeed.videoWidth; c.height = $camFeed.videoHeight;
  c.getContext('2d').drawImage($camFeed, 0, 0);
  imgSrc = c.toDataURL('image/png');
  switchTab('upload');
  showPreview(imgSrc);
}

function stopCamera() {
  if (stream) { stream.getTracks().forEach(t => t.stop()); stream = null; }
  $camFeed.classList.remove('on'); $camFeed.srcObject = null;
  $camPh.style.display = '';
  $btnCamStart.disabled = false; $btnCapture.disabled = true;
  $btnCamStop.classList.add('hidden');
}

// ================================================================
//  5 · Prediction
// ================================================================
async function runPrediction() {
  if (!modelReady) { alert(t('model_loading_alert')); return; }
  if (!imgSrc) return;

  $btnScan.classList.add('busy');
  $btnScan.disabled = true;
  $resultsBox.innerHTML = '';

  try {
    const img = new Image();
    await new Promise((res, rej) => { img.onload = res; img.onerror = rej; img.src = imgSrc; });
    const preds = await model.predict(img);
    renderResults(preds);
  } catch (err) {
    $resultsBox.innerHTML = errCard(err.message || 'Analysis failed — please try again.');
  } finally {
    $btnScan.classList.remove('busy');
    $btnScan.disabled = false;
  }
}

function errCard(msg) {
  return `<div class="results"><div class="res-card"><div class="res-body">
    <div class="dx-banner warn"><div class="dx-ico"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg></div>
    <div class="dx-txt"><h4>Error</h4><p>${msg}</p></div></div></div></div></div>`;
}

// ================================================================
//  SVG Icons for results (professional, no emoji)
// ================================================================
const ICONS = {
  danger: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="15" y1="9" x2="9" y2="15"/><line x1="9" y1="9" x2="15" y2="15"/></svg>',
  success: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>',
  warn: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>',
  pulse: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>',
  stethoscope: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4.8 2.62A2 2 0 0 0 3 4.5v5a7 7 0 0 0 7 7h.5"/><path d="M20.2 2.62A2 2 0 0 1 22 4.5v5a7 7 0 0 1-7 7h-.5"/><circle cx="14.5" cy="18.5" r="2.5"/><path d="M14.5 21v1a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3.5"/></svg>',
};

// ================================================================
//  6 · Render results + Medical Guidance
// ================================================================
function renderResults(preds) {
  const sorted = [...preds].sort((a, b) => b.probability - a.probability);
  const top = sorted[0];
  const pct = (top.probability * 100).toFixed(1);

  // Classify top result
  const cl = top.className.toLowerCase();
  let type;
  if (cl.includes('yes') && !cl.includes('no'))       type = 'tumor';
  else if (cl.includes('no tumor') || (cl.includes('no ') && !cl.includes('not '))) type = 'clear';
  else type = 'notmri';

  const bannerData = {
    tumor:  { c:'danger',  icon: ICONS.danger,  tKey:'dx_tumor_t',  dKey:'dx_tumor_d' },
    clear:  { c:'success', icon: ICONS.success, tKey:'dx_clear_t',  dKey:'dx_clear_d' },
    notmri: { c:'warn',    icon: ICONS.warn,    tKey:'dx_notmri_t', dKey:'dx_notmri_d' },
  };
  const b = bannerData[type];

  // Build bars ONLY for tumor/clear — NOT for notmri
  let barsHTML = '';
  if (type !== 'notmri') {
    sorted.forEach(p => {
      const v = (p.probability * 100).toFixed(1);
      const n = p.className.toLowerCase();
      let cc = 'warn', lbl = p.className;
      if (n.includes('yes') && !n.includes('no'))       { cc = 'danger';  lbl = t('bar_tumor'); }
      else if (n.includes('no tumor') || (n.includes('no ') && !n.includes('not '))) { cc = 'success'; lbl = t('bar_clear'); }
      else if (n.includes('not '))                       { cc = 'warn';    lbl = t('bar_notmri'); }

      barsHTML += `
        <div class="bar-item">
          <div class="bar-row"><span class="bar-label"><span class="bar-dot ${cc}"></span>${lbl}</span><span class="bar-val ${cc}">${v}%</span></div>
          <div class="track"><div class="fill ${cc}" style="width:0%" data-w="${v}"></div></div>
        </div>`;
    });
    barsHTML = `<div class="bars">${barsHTML}</div>`;
  }

  // Medical guidance
  const guideKeys = {
    tumor:  { title: 'guide_tumor_title', body: 'guide_tumor_body' },
    clear:  { title: 'guide_clear_title', body: 'guide_clear_body' },
    notmri: { title: 'guide_notmri_title', body: 'guide_notmri_body' },
  };
  const gk = guideKeys[type];
  const guidanceHTML = `
    <div class="med-guide">
      <div class="med-guide-head">${ICONS.stethoscope} ${t(gk.title)}</div>
      <div class="med-guide-body">${t(gk.body, { pct })}</div>
    </div>`;

  // Timestamp
  const ts = new Date().toLocaleString(currentLang === 'ar' ? 'ar-SA' : currentLang === 'fr' ? 'fr-FR' : 'en-US', { hour:'2-digit', minute:'2-digit', day:'numeric', month:'short', year:'numeric' });

  $resultsBox.innerHTML = `
    <div class="results">
      <div class="res-card">
        <div class="res-head">
          <h3>${ICONS.pulse} ${t('res_title')}</h3>
          <span class="res-time">${ts}</span>
        </div>
        <div class="res-body">
          <div class="dx-banner ${b.c}">
            <div class="dx-ico">${b.icon}</div>
            <div class="dx-txt"><h4>${t(b.tKey)}</h4><p>${t(b.dKey, { pct })}</p></div>
          </div>
          ${barsHTML}
          ${guidanceHTML}
          <div class="disclaimer">
            <p>${t('disclaimer')}</p>
          </div>
        </div>
      </div>
    </div>`;

  // Animate bars
  if (type !== 'notmri') {
    requestAnimationFrame(() => {
      setTimeout(() => {
        document.querySelectorAll('.fill[data-w]').forEach(el => { el.style.width = el.dataset.w + '%'; });
      }, 80);
    });
  }

  $resultsBox.scrollIntoView({ behavior: 'smooth', block: 'start' });
}

// ================================================================
//  8 · Enable scan button when model finishes loading
// ================================================================
const observer = new MutationObserver(() => {
  if (modelReady && imgSrc) $btnScan.disabled = false;
});
observer.observe($status, { attributes: true, attributeFilter: ['class'] });

// ================================================================
//  9 · Init
// ================================================================
document.addEventListener('DOMContentLoaded', () => {
  initTheme();
  setLanguage(currentLang);
  loadModel();
});
